AL:
  budget: 0.3
  initial_labeled: 0.1
  query: 0.01
  query_strategy: "URPCMGQuery"

Dataset:
  data_dir: "data/ACDCprecessed"
  batch_size: 32
  num_workers: 4

Training:
  output_dir:
  device: "cuda:0"
  iter_max: 30000
  iter_valid: 100
  lr: 2.5e-3
  weight_decay: 1e-5
  forget_weight: false
  seed: 3407

Network:
  ndf: 16

