AL:
  budget: 0.3
  initial_labeled: 0.1
  query: 0.01
  query_strategy: "RandomQuery"

Dataset:
  data_dir: "data/ACDCprecessed"
  batch_size: 32 #for dev
  num_workers: 4
  input_size: 192

Training:
  output_dir:
  device: "cuda:0"
  iter_max: 30000
  iter_valid: 100
  early_stop_patience: 10000
  lr: 2.5e-3
  lr_gamma: 0.5
  ReduceLROnPlateau_patience: 4000
  weight_decay: 0.00001
  seed: 3407
Network:
  classnum: 4
  ndf: 16

